apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: networking
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nPn3L+zocs4zh4fKpG0MjdAF54PgHnTpr3mwoUrHQBI6dhrIGwjzU9OQBAsYmRCJ96WPVwVlUyRhtX6reDYEdaNWobIuApVsOj8Wk0litFPHomllYTS5zLteKoqTP8LYij/0v7C8EfDFiUFsqKLdPOvgABBUnjJWLTyDRAYrtHCFE2rE7dQ9424nlZkXyLseTZhO3MhG2dWZTBzJdXz4+n0eSs8gSwIW9G0MkyTrjOR3viJq1IxPQ2A2lBRvjVuOxiY2Mzl6JhyFo2oU39oOyDJWZPdYhs+H2fdo4GdgDJTD2A+Rv1LOpaXM6iKrrcth2wGhS02oNzA=,iv:nu5g6yIIfSEjvi4XCc1ZQiSCUbnuiyDIk267ITuOXLg=,tag:UsDQ0KHVYH6Y3Wu/L+nOyw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycko4NmtVK2gvdkhpUVpw
            MFJERWJUSkVnWkltL3h5KzVvMXl2NlJHMFhrCnIvNHNCd0JmM3A4ZzY2S3Mrajl4
            cWpjb1ljVmtUVXI3MFFjUnNIK2N0cnMKLS0tIEYyNGRETzZRaHE2M3NjNWhXaDdt
            ZFl0eVBoZkZBUnVjU1YrNUdSUmx6OVUKtXy/CTW5dk2kPPAd/IG6zDrcvFLqoUu3
            5NGZCA6lUHXWIuxrM2yRRLO5rWjouHbM+jNdmYOvtWz+Xytm28xmcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T06:44:16Z"
    mac: ENC[AES256_GCM,data:9m1OmbY75JT4c1ftSMwF0eQS2U0v3ziF6URmpwJ9jP7hLO1uSD7sw74sFLZ1TIUK7RJN73ExB/jA7w9P2+qH2vCRR4RvL3IgiJkHzz0YYYxWJ6msuKWH/3Vrr7OjvV1Co8I+QRu8asVEx5mpC561z/7MSM1DF2pV7yE9xG00Dio=,iv:3PRZ+Bw8XhetuO2YVKN7UTTgflDB60IiNvVK8tNRPS0=,tag:Nxssc3sHfVaGOTS9iDLrfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
